### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by aracelicaes**
Checking linters.

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi Araceli👏,
You have done a good job so far,
Here are a few changes we have to do to get this project approved.

* [x] Let use background gradient for the navbar refer to [this](https://www.w3schools.com/css/css3_gradients.asp) 

* [x] it should be made of nine different buttons with the Apple logo on the leftmost section and a search field on the rightmost section. 🙂 
In this case, let us keep it simple by doing  this ```<li> <a href="#" >store</a> </li>``` do this for each case in the navbar😇

* [x] let us set ```versebe```, ```everyoneHas```, and ```watchYourVerse"``` as images. You can grab those images by inspecting the original page.
> note:  try as much as possible not to use ```ID``` selectors

* [x] let us replace all ```ID``` selectors with ```class```🙂
* [x] Let us modify our code to get rid of the horizontal scroll on the page.🙂 
This how our current page looks like.
Screenshot from 2019-10-29 20-38-21
 set with of ```aside``` to 100%🙂
## That is it  do these changes and submit the project for review🙂

feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.
#### Happy coding🙂

**Comment by aracelicaes** [comment]
I changed most of the id's to classes. However, I searched in the WEB for best practices to see which one is best to use, it seems that it's up to user's discretion, but also that id's should be unique and to identify UNIQUE elements and classes to identify  several elements with the same class name. So...the elements I have do NOT repeat themselves in most cases. In my understanding, I should be using ID because they are unique and I need to give them specific styling. I also gathered some resources where this info is confirmed, I have added them below. Thank you. 

https://css-tricks.com/the-difference-between-id-and-class/
https://stackoverflow.com/questions/298607/css-best-practice-about-id-and-class
https://www.htmldog.com/guides/css/intermediate/classid/
https://stackoverflow.com/questions/12889362/difference-between-id-and-class-in-css-and-when-to-use-it

**Comment by ebukaume** [comment]
## Approved! 

Hi @aracelicaes :wave: 

**Congratulations! You are approved to merge this branch.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Pull request merged**
